
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: persuadir_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: persuadir_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: persuadir
  pool: 5
  username: persuadir
  password: lima1234
  socket: /var/run/mysqld/mysqld.sock