theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
plugins:
  - table
  - fullscreen
  - emotions
  - paste

theme_advanced_buttons1:
  - bold
  - italic
  - underline
  - strikethrough
  - justifyleft
  - justifycenter
  - justifyright
  - justifyfull
  - bullist
  - numlist
  - outdent
  - indent
  - hr
  - removeformat
  - formatselect
  - sub
  - sup
theme_advanced_buttons2:
  # - forecolor
  - backcolor
  # - forecolorpicker
  - backcolorpicker
  - charmap
  - visualaid
  - anchor
  - newdocument
  - blockquote
  - cut
  - copy
  - paste
  - pastetext
  - pasteword
  - undo
  - redo
  - link
  - unlink
theme_advanced_buttons3:
  - image
  - tablecontrols
  - fullscreen
  - emotions
  - cleanup
  - code
